#!/bin/sh
# Copyright 2010 Antoine Bertin
# <diaoulael [ignore this] at gmail period com>
#
# This file is part of syno-packager.
#
# syno-packager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# syno-packager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with syno-packager.  If not, see <http://www.gnu.org/licenses/>.

# Directories
CMDIR=/usr/local/cron-manager
CMSHR=$CMDIR/share
CMVAR=$CMDIR/var

preinst ()
{
	# Find the CPU architecture
	synoinfo=`get_key_value /etc.defaults/synoinfo.conf unique`
	arch=`echo $synoinfo | cut -d_ -f2`

	# Check if toolbox is installed
	if [ ! -d /usr/local/toolbox ]; then
		echo "toolbox SPK is not installed. Install it and try again."
		exit 1
	fi

	exit 0
}

postinst ()
{
	# Create the view directory
	mkdir -p $CMDIR

	# Create symlinks to the installation ditectory
	ln -s ${SYNOPKG_PKGDEST}/share $CMSHR
	ln -s ${SYNOPKG_PKGDEST}/var $CMVAR

	# Correct the files ownership
	chown -R root:root ${SYNOPKG_PKGDEST}

	exit 0
}

preuninst ()
{
	exit 0
}

postuninst ()
{
	# Remove symlinks from /usr/local/cron-manager
	rm -f $CMSHR
	rm -f $CMVAR

	# Remove the view directory
	rmdir $CMDIR

	exit 0
}

preupgrade ()
{
	exit 0
}

postupgrade ()
{
	exit 0
}
