#!/bin/sh
# Copyright 2010 Antoine Bertin
# <diaoulael [ignore this] at users.sourceforge period net>
#
# This file is part of syno-packager.
#
# syno-packager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# syno-packager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with syno-packager.  If not, see <http://www.gnu.org/licenses/>.

# Directories
NZBDIR=/usr/local/nzbget
NZBVAR=$NZBDIR/var
NZBLIB=$NZBDIR/lib
NZBETC=$NZBDIR/etc
NZBBIN=$NZBDIR/bin
NZBSHR=$NZBDIR/share
NZBDLS=$NZBDIR/downloads
NZBTMI=$NZBSHR/terminfo

# Binaries
NZBEXE=$NZBBIN/nzbget
NICEXE=$NZBBIN/nice
IONEXE=$NZBBIN/ionice
ADDUSREXE=$NZBBIN/adduser
DELUSREXE=$NZBBIN/deluser
SUEXE=/bin/su
PSEXE=ps

# Files
NZBCNF=$NZBETC/nzbget.conf
NZBLOG=$NZBVAR/nzbget-spk.log

# User
NZBEXEUSR=nzbgetuser

preinst ()
{
	# Find the CPU architecture
	synoinfo=`get_key_value /etc.defaults/synoinfo.conf unique`
	arch=`echo $synoinfo | cut -d_ -f2`

	# Check if the architecture is supported
	if ! echo "$arch" | grep -q "%SPK_ARCH%"; then
		echo "Your architecture is not supported by this package. Architecture  : '$arch'. Synology info : '$synoinfo'. Required : '%SPK_ARCH%'."
		exit 1
	fi
	exit 0
}

postinst ()
{
	# Create the view directory
	mkdir -p $NZBDIR
	mkdir -p /usr/local/bin

	# Create symlinks to the installation ditectory
	ln -s ${SYNOPKG_PKGDEST}/bin $NZBBIN
	ln -s ${SYNOPKG_PKGDEST}/lib $NZBLIB
	ln -s ${SYNOPKG_PKGDEST}/var $NZBVAR
	ln -s ${SYNOPKG_PKGDEST}/etc $NZBETC
	ln -s ${SYNOPKG_PKGDEST}/share $NZBSHR
	ln -s ${SYNOPKG_PKGDEST}/downloads $NZBDLS

	# Create symlink
	ln -s $NZBEXE /usr/local/bin/nzbget

	# Add the web service
	cp -R ${SYNOPKG_PKGDEST}/nzbgetweb /var/services/web/nzbgetweb
	cp $NZBETC/settings.php /var/services/web/nzbgetweb/
	chmod 777 /var/services/web/nzbgetweb/settings.php

	# Create NZB specific user
	$ADDUSREXE $NZBEXEUSR -h "$NZBVAR" -s "/sbin/nologin" -G "users" -D -H

	# Correct the files ownership
	chown -R $NZBEXEUSR:root ${SYNOPKG_PKGDEST}

	# Correct the files permission
	chmod 550 $NZBBIN/*
	chmod 550 $NZBLIB/*
	chmod 770 $NZBVAR/*
	chmod 777 $NZBETC/*

	exit 0
}

preuninst ()
{
	# Remove the user
	$DELUSREXE $NZBEXEUSR

	exit 0
}

postuninst ()
{
	# Remove symlink
	rm -f /usr/local/bin/nzbget

	# Remove symlinks from /usr/local/nzbget
	rm -f $NZBBIN
	rm -f $NZBLIB
	rm -f $NZBVAR
	rm -f $NZBETC
	rm -f $NZBSHR
	rm -f $NZBDLS

	# Remove the view directory
	rmdir $NZBDIR

	# Remove the web service
	rm -rf /var/services/web/nzbgetweb

	exit 0
}

preupgrade ()
{
	exit 1
}

postupgrade ()
{
	exit 1
}
