#!/bin/sh
# Copyright 2010 Antoine Bertin
# <diaoulael [ignore this] at users.sourceforge period net>
#
# This file is part of syno-packager.
#
# syno-packager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# syno-packager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with syno-packager.  If not, see <http://www.gnu.org/licenses/>.

# Find the CPU architecture
synoinfo=`get_key_value /etc.defaults/synoinfo.conf unique`
arch=`echo $synoinfo | cut -d_ -f2`

preinst ()
{
	# Check if the architecture is supported
	if ! echo "$arch" | grep -q "%SPK_ARCH%"; then
		echo "Your architecture is not supported by this package. Architecture  : '$arch'. Synology info : '$synoinfo'. Required : '%SPK_ARCH%'."
		exit 1
	fi
	exit 0
}

postinst ()
{
	# Create the view directory
	mkdir -p /usr/local/nzbget
	mkdir -p /usr/local/bin

	# Create symlinks to the installation ditectory
	ln -s ${SYNOPKG_PKGDEST}/bin /usr/local/nzbget/bin
	ln -s ${SYNOPKG_PKGDEST}/lib /usr/local/nzbget/lib
	ln -s ${SYNOPKG_PKGDEST}/var /usr/local/nzbget/var
	ln -s ${SYNOPKG_PKGDEST}/etc /usr/local/nzbget/etc

	# Create symlink
	ln -s /usr/local/nzbget/bin/nzbget /usr/local/bin/nzbget

	# Add the web service
	cp -R ${SYNOPKG_PKGDEST}/nzbgetweb /var/services/web/nzbgetweb

	# Create NZB specific user
	/usr/local/nzbget/bin/adduser nzbduser -h "/usr/local/nzbget/var" -s "/sbin/nologin" -G "users" -D -H

	# Correct the files ownership
	chown -R nzbduser:root ${SYNOPKG_PKGDEST}

	# Correct the files permission
	chmod 550 /usr/local/nzbget/bin/*
	chmod 550 /usr/local/nzbget/lib/*
	chmod 770 /usr/local/nzbget/var/*
	chmod 770 /usr/local/nzbget/etc/*

	exit 0
}

preuninst ()
{
	# Remove the user
	/usr/local/nzbget/bin/deluser nzbduser

	exit 0
}

postuninst ()
{
	# Remove symlink
	rm -f /usr/local/bin/nzbget

	# Remove symlinks from /usr/local/nzbget
	rm -f /usr/local/nzbget/bin
	rm -f /usr/local/nzbget/lib
	rm -f /usr/local/nzbget/var
	rm -f /usr/local/nzbget/etc
	rm -f /usr/local/nzbget/nzbgetweb

	# Remove the view directory
	rmdir /usr/local/nzbget

	# Remove the web service
	rm -rf /var/services/web/nzbgetweb

	exit 0
}

preupgrade ()
{
	exit 1
}

postupgrade ()
{
	exit 1
}
