#!/bin/sh
# Copyright 2010 Antoine Bertin
# <diaoulael [ignore this] at users.sourceforge period net>
#
# This file is part of syno-packager.
#
# syno-packager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# syno-packager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with syno-packager.  If not, see <http://www.gnu.org/licenses/>.

# Directories
NZBDIR=/usr/local/nzbget
NZBVAR=$NZBDIR/var
NZBLIB=$NZBDIR/lib
NZBETC=$NZBDIR/etc
NZBBIN=$NZBDIR/bin
NZBSHR=$NZBDIR/share
NZBDLS=$NZBDIR/downloads
NZBTMI=$NZBSHR/terminfo

# Binaries
NZBEXE=$NZBBIN/nzbget
NICEXE=$NZBBIN/nice
IONEXE=$NZBBIN/ionice
ADDUSREXE=$NZBBIN/adduser
DELUSREXE=$NZBBIN/deluser
SUEXE=/bin/su
PSEXE=ps

# Files
NZBCNF=$NZBETC/nzbget.conf
NZBLOG=$NZBVAR/nzbget-spk.log

# User
NZBEXEUSR=nzbgetuser

start_daemon ()
{
	# Log
	echo `date`" : Starting nzbget..." >> $NZBLOG

	# Start nzbget
	$SUEXE $NZBEXEUSR -s /bin/sh -c "LD_LIBRARY_PATH=$NZBLIB $NICEXE -n15 $IONEXE -c2 -n4 $NZBEXE -c $NZBCNF -D >> $NZBLOG 2>&1"
}

stop_daemon ()
{
	# Log
	echo `date`" : Stoping nzbget..." >> $NZBLOG

	# Kill daemon
	$SUEXE $NZBEXEUSR -s /bin/sh -c "LD_LIBRARY_PATH=$NZBLIB $NICEXE -n15 $IONEXE -c2 -n4 $NZBEXE -c $NZBCNF -Q"
	sleep 1

	# Wait until nzbget is really dead (may take some time)
	counter=20
	while [ $counter -gt 0 ] 
	do
		daemon_status || break
		let counter=counter-1
		sleep 1
	done
}

launch_client ()
{
	# Log
	echo `date`" : Launching nzbget client..." >> $NZBLOG

	# Open client
	TERMINFO=$NZBTMI LD_LIBRARY_PATH=$NZBLIB $NICEXE -n15 $IONEXE -c2 -n4 $NZBEXE -c $NZBCNF -C
}

daemon_status ()
{
	[ "`$SUEXE $NZBEXEUSR -s /bin/sh -c \"$PSEXE | grep $NZBEXE | grep -v grep\"`" != "" ]
}


case $1 in
	start)
		if daemon_status; then
			echo "nzbget daemon already running !"
			exit 0
		else
			echo "Starting nzbget daemon..."
			start_daemon
			exit $?
		fi
		;;
	stop)
		echo "Stopping nzbget daemon..."
		stop_daemon
		exit 0
		;;
	restart)
		stop_daemon
		start_daemon
		exit $?
		;;
	status)
		if daemon_status; then
			echo "Running"
			exit 0
		else
			echo "Not running"
			exit 1
		fi
		;;
	client)
		echo "Opening nzbget client..."
		launch_client
		exit 0
		;;
	log)
		echo $NZBLOG
		exit 0
		;;
	*)
		exit 1
		;;
esac
