#!/bin/sh
# Copyright 2010 Antoine Bertin
# <diaoulael [ignore this] at users.sourceforge period net>
#
# This file is part of syno-packager.
#
# syno-packager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# syno-packager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with syno-packager.  If not, see <http://www.gnu.org/licenses/>.

# Common
CFEDIR=/usr/local/CFE
CFEAPP=$CFEDIR/app
CFEVAR=$CFEDIR/var
CFEENABLED=/var/packages/CFE/enabled

# Files
CFELOG=$CFEVAR/CFE-spk.log

start_daemon ()
{
	# Log
	echo `date`" : Starting CFE..." >> $CFELOG
}

stop_daemon ()
{
	# Log
	echo `date`" : Stoping CFE..." >> $CFELOG
}

daemon_status ()
{
	[ -f $CFEENABLED ]
}

case $1 in
	start)
		if daemon_status; then
			echo "CFE already running!"
			exit 0
		else
			echo "Starting CFE..."
			start_daemon
			exit $?
		fi
		;;
	stop)
		echo "Stopping CFE..."
		stop_daemon
		exit $?
		;;
	restart)
		stop_daemon
		start_daemon
		exit $?
		;;
	reload)
		if daemon_status; then
			reload_daemon
		fi
		exit $?
		;;
	status)
		if daemon_status; then
			echo "Running"
			exit 0
		else
			echo "Not running"
			exit 1
		fi
		;;
	log)
		echo $CFELOG
		exit 0
		;;
	*)
		exit 1
		;;
esac
