#!/bin/sh
# Copyright 2010 Antoine Bertin
# <diaoulael [ignore this] at users.sourceforge period net>
#
# This file is part of syno-packager.
#
# syno-packager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# syno-packager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with syno-packager.  If not, see <http://www.gnu.org/licenses/>.

# Directories
INTDIR=/usr/local/inotify-tools
INTLIB=$INTDIR/lib
INTBIN=$INTDIR/bin

# Binaries
INTWAIEXE=$INTBIN/inotifywait
INTWATEXE=$INTBIN/inotifywatch

preinst ()
{
	# Find the CPU architecture
	synoinfo=`get_key_value /etc.defaults/synoinfo.conf unique`
	arch=`echo $synoinfo | cut -d_ -f2`

	# Check if the architecture is supported
	if ! echo "$arch" | grep -q "%SPK_ARCH%"; then
		echo "Your architecture is not supported by this package. Architecture  : '$arch'. Synology info : '$synoinfo'. Required : '%SPK_ARCH%'."
		exit 1
	fi
	exit 0
}

postinst ()
{
	# Create the view directory
	mkdir -p $INTDIR
	mkdir -p /usr/local/bin

	# Create symlinks to the installation ditectory
	ln -s ${SYNOPKG_PKGDEST}/bin $INTBIN
	ln -s ${SYNOPKG_PKGDEST}/lib $INTLIB

	# Create symlinks
	ln -s $INTWAIEXE /usr/local/bin/inotifywait
	ln -s $INTWATEXE /usr/local/bin/inotifywatch

	# Correct the files ownership
	chown -R root:root ${SYNOPKG_PKGDEST}

	# Correct the files permission
	chmod 777 $INTBIN/*
	chmod 777 $INTLIB/*

	exit 0
}

preuninst ()
{
	exit 0
}

postuninst ()
{
	# Remove symlink
	rm -f /usr/local/bin/inotifywait
	rm -f /usr/local/bin/inotifywatch

	# Remove symlinks from /usr/local/inotify-tools
	rm -f $INTBIN
	rm -f $INTLIB

	# Remove the view directory
	rmdir $INTDIR

	exit 0
}

preupgrade ()
{
	exit 1
}

postupgrade ()
{
	exit 1
}
