#!/bin/sh
# Copyright 2010 Antoine Bertin
# <diaoulael [ignore this] at users.sourceforge period net>
#
# This file is part of syno-packager.
#
# syno-packager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# syno-packager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with syno-packager.  If not, see <http://www.gnu.org/licenses/>.

preinst ()
{
	# Find the CPU architecture
	synoinfo=`get_key_value /etc.defaults/synoinfo.conf unique`
	arch=`echo $synoinfo | cut -d_ -f2`

	# Check if the architecture is supported
	if ! echo "$arch" | grep -q "%SPK_ARCH%"; then
		echo "Your architecture is not supported by this package. Architecture  : '$arch'. Synology info : '$synoinfo'. Required : '%SPK_ARCH%'."
		exit 1
	fi
	exit 0
}

postinst ()
{
	# Create the view directory
	mkdir -p /usr/local/SABnzbd
	mkdir -p /usr/local/bin

	# Create symlinks to the installation ditectory
	ln -s ${SYNOPKG_PKGDEST}/bin /usr/local/SABnzbd/bin
	ln -s ${SYNOPKG_PKGDEST}/lib /usr/local/SABnzbd/lib
	ln -s ${SYNOPKG_PKGDEST}/include /usr/local/SABnzbd/include
	ln -s ${SYNOPKG_PKGDEST}/SABnzbd /usr/local/SABnzbd/SABnzbd
	ln -s ${SYNOPKG_PKGDEST}/var /usr/local/SABnzbd/var
	ln -s ${SYNOPKG_PKGDEST}/etc /usr/local/SABnzbd/etc

	# Create SABnzbd specific user
	/usr/local/SABnzbd/bin/adduser sabnzbduser -h "/usr/local/SABnzbd/var" -s "/sbin/nologin" -G "users" -D -H

	# Correct the files ownership
	chown -R sabnzbduser:root ${SYNOPKG_PKGDEST}

	# Create symlinks
	ln -s /usr/local/SABnzbd/bin/cfg.parser /usr/local/bin/cfg.parser
	ln -s /usr/local/SABnzbd/bin/python /usr/local/bin/python
	ln -s /usr/local/SABnzbd/bin/nice /usr/local/bin/nice
	ln -s /usr/local/SABnzbd/bin/renice /usr/local/bin/renice
	ln -s /usr/local/SABnzbd/bin/ionice /usr/local/bin/ionice
	ln -s /usr/local/SABnzbd/bin/par2 /usr/local/bin/par2
	ln -s /usr/local/SABnzbd/bin/ps /usr/local/bin/ps
	ln -s /usr/local/SABnzbd/bin/par2create /usr/local/bin/par2create
	ln -s /usr/local/SABnzbd/bin/par2verify /usr/local/bin/par2verify
	ln -s /usr/local/SABnzbd/bin/par2repair /usr/local/bin/par2repair

	# Correct the files permission
	chmod 550 /usr/local/SABnzbd/bin/*
	chmod 550 /usr/local/SABnzbd/lib/*
	chmod 770 /usr/local/SABnzbd/var/*
	chmod 770 /usr/local/SABnzbd/etc/*

	exit 0
}

preuninst ()
{
	# Remove the user
	/usr/local/SABnzbd/bin/deluser sabnzbduser

	exit 0
}

postuninst ()
{
	# Remove symlinks
	rm -f /usr/local/bin/cfg.parser
	rm -f /usr/local/bin/python
	rm -f /usr/local/bin/nice
	rm -f /usr/local/bin/renice
	rm -f /usr/local/bin/ionice
	rm -f /usr/local/bin/par2
	rm -f /usr/local/bin/ps
	rm -f /usr/local/bin/par2create
	rm -f /usr/local/bin/par2verify
	rm -f /usr/local/bin/par2repair

	# Remove symlinks from /usr/local/SABnzbd
	rm -f /usr/local/SABnzbd/bin
	rm -f /usr/local/SABnzbd/lib
	rm -f /usr/local/SABnzbd/include
	rm -f /usr/local/SABnzbd/SABnzbd
	rm -f /usr/local/SABnzbd/var
	rm -f /usr/local/SABnzbd/etc

	# Remove the view directory
	rmdir /usr/local/SABnzbd

	exit 0
}

preupgrade ()
{
	exit 1
}

postupgrade ()
{
	exit 1
}
