#!/bin/sh
# Copyright 2010 Antoine Bertin
# <diaoulael [ignore this] at users.sourceforge period net>
#
# This file is part of syno-packager.
#
# syno-packager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# syno-packager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with syno-packager.  If not, see <http://www.gnu.org/licenses/>.

preinst ()
{
	# Check if Python is installed
	if [ ! -d /usr/local/Python ]; then
		echo "Python SPK is not installed. Install it and try again."
		exit 1
	fi
	
	# Check if toolbox is installed
	if [ ! -d /usr/local/toolbox ]; then
		echo "toolbox SPK is not installed. Install it and try again."
		exit 1
	fi

	exit 0
}

postinst ()
{
	# Create the view directory
	mkdir -p /usr/local/SABnzbd

	# Create symlinks to the installation ditectory
	ln -s ${SYNOPKG_PKGDEST}/SABnzbd /usr/local/SABnzbd/SABnzbd
	ln -s ${SYNOPKG_PKGDEST}/var /usr/local/SABnzbd/var
	ln -s ${SYNOPKG_PKGDEST}/etc /usr/local/SABnzbd/etc
	ln -s ${SYNOPKG_PKGDEST}/share /usr/local/SABnzbd/share

	# Create SABnzbd specific user
	/usr/local/bin/adduser sabnzbduser -h "/usr/local/SABnzbd/var" -s "/sbin/nologin" -G "users" -D -H

	# Correct the files ownership
	chown -R sabnzbduser:root ${SYNOPKG_PKGDEST}

	# Correct the files permission
	chmod 770 /usr/local/SABnzbd/var/*
	chmod 770 /usr/local/SABnzbd/etc/*

	exit 0
}

preuninst ()
{
	# Remove the user
	/usr/local/bin/deluser sabnzbduser

	exit 0
}

postuninst ()
{
	# Remove symlinks from /usr/local/SABnzbd
	rm -f /usr/local/SABnzbd/SABnzbd
	rm -f /usr/local/SABnzbd/var
	rm -f /usr/local/SABnzbd/etc
	rm -f /usr/local/SABnzbd/share

	# Remove the view directory
	rmdir /usr/local/SABnzbd

	exit 0
}

preupgrade ()
{
	exit 1
}

postupgrade ()
{
	exit 1
}
