#!/bin/sh
# Copyright 2010 Antoine Bertin
# <diaoulael [ignore this] at users.sourceforge period net>
#
# This file is part of syno-packager.
#
# syno-packager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# syno-packager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with syno-packager.  If not, see <http://www.gnu.org/licenses/>.

UPGRADELOCK=/tmp/transmission.upgrade.lock

preinst ()
{
	# Find the CPU architecture
	synoinfo=`get_key_value /etc.defaults/synoinfo.conf unique`
	arch=`echo $synoinfo | cut -d_ -f2`

	# Check if the architecture is supported
	if ! echo "$arch" | grep -q "%SPK_ARCH%"; then
		echo "Your architecture is not supported by this package. Architecture  : '$arch'. Synology info : '$synoinfo'. Required : '%SPK_ARCH%'."
		exit 1
	fi

	# Check if toolbox is installed
	if [ ! -d /usr/local/toolbox ]; then
		echo "toolbox SPK is not installed. Install it and try again."
		exit 1
	fi

	exit 0
}

postinst ()
{
	# Create the view directory
	mkdir -p /usr/local/transmission
	mkdir -p /usr/local/bin

	# Create symlinks to the installation ditectory
	ln -s ${SYNOPKG_PKGDEST}/bin /usr/local/transmission/bin
	ln -s ${SYNOPKG_PKGDEST}/lib /usr/local/transmission/lib
	ln -s ${SYNOPKG_PKGDEST}/share /usr/local/transmission/share
	ln -s ${SYNOPKG_PKGDEST}/var /usr/local/transmission/var
	ln -s ${SYNOPKG_PKGDEST}/etc /usr/local/transmission/etc

	# Create symlink
	ln -s /usr/local/transmission/bin/transmission-daemon /usr/local/bin/transmission-daemon

	# Create transmission specific user
	/usr/local/bin/adduser transmission -h "/usr/local/transmission/var" -s "/sbin/nologin" -G "users" -D -H

	# Correct the files ownership
	chown -R transmission:root ${SYNOPKG_PKGDEST}


	# Restore the config file if we're upgrading
	if [ -f $UPGRADELOCK ]; then
		mv /tmp/settings.json ${SYNOPKG_PKGDEST}/etc/
		chown transmission:root ${SYNOPKG_PKGDEST}/etc/settings.json
	fi

	# Correct the files permission
	chmod 555 /usr/local/transmission/bin/*
	chmod 555 /usr/local/transmission/lib/*

	exit 0
}

preuninst ()
{
	# Remove the user if we're not upgrading
	if [ ! -f $UPGRADELOCK ]; then
		/usr/local/bin/deluser transmission
	fi

	# Save the config file if we're upgrading
	if [ -f $UPGRADELOCK ]; then
		cp ${SYNOPKG_PKGDEST}/etc/settings.json /tmp/
	fi

	exit 0
}

postuninst ()
{
	# Remove symlink
	rm -f /usr/local/bin/transmission-daemon

	# Remove symlinks from /usr/local/transmission
	rm -f /usr/local/transmission/bin
	rm -f /usr/local/transmission/lib
	rm -f /usr/local/transmission/share
	rm -f /usr/local/transmission/var
	rm -f /usr/local/transmission/etc

	# Remove the view directory
	rmdir /usr/local/transmission

	exit 0
}

preupgrade ()
{
	touch $UPGRADELOCK

	exit 0
}

postupgrade ()
{
	rm -f $UPGRADELOCK

	exit 0
}
