#!/bin/sh
# Copyright 2010 Antoine Bertin
# <diaoulael [ignore this] at users.sourceforge period net>
#
# This file is part of syno-packager.
#
# syno-packager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# syno-packager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with syno-packager.  If not, see <http://www.gnu.org/licenses/>.

# Common
TRDIR=/usr/local/transmission
TRVAR=$TRDIR/var
TRLIB=$TRDIR/lib
TRETC=$TRDIR/etc
TRSHR=$TRDIR/share
TREXE=$TRDIR/bin/transmission-daemon
SUEXE=/bin/su
PSEXE=/usr/local/bin/ps
TRUSR=transmission
SYNO3APP=/usr/syno/synoman/webman/3rdparty

# Files
TRCNF=$TRETC/settings.json
TRPID=$TRVAR/transmission.pid
TRLOG=$TRVAR/transmission-spk.log

start_daemon ()
{
	# Log
	echo `date`" : Starting transmission daemon..." >> $TRLOG

	# Start transmission
	$SUEXE $TRUSR -s /bin/sh -c "TRANSMISSION_WEB_HOME=$TRSHR/transmission/web/ LD_LIBRARY_PATH=$TRLIB $TREXE -g $TRETC -x $TRPID >> $TRLOG 2>&1"

	# Install the application in the main interface.
	if [ -d $SYNO3APP ]
	then
		rm -f $SYNO3APP/transmission
		ln -s $TRSHR/3rdparty $SYNO3APP/transmission
	fi
}

stop_daemon ()
{
	# Log
	echo `date`" : Stoping transmission daemon..." >> $TRLOG

	# Remove the application from the main interface if it was previously added.
	if [ -h $SYNO3APP/transmission ]
	then
		rm -f $SYNO3APP/transmission
	fi

	# Kill daemon
	if [ -f $TRPID ]; then
		kill `cat $TRPID`
		rm -f $TRPID
		echo " ok"
	else
		echo " error : Can't find PID file!"
		killall transmission-daemon
	fi
	sleep 1

	# Wait until transmission is really dead (may take some time).
	counter=20
	while [ $counter -gt 0 ] 
	do
		daemon_status || exit 0
		let counter=counter-1
		sleep 1
	done

	exit 1
}

daemon_status ()
{
	[ "`$SUEXE $TRUSR -s /bin/sh -c \"$PSEXE x | grep transmission-daemon | grep -v grep\"`" != "" ]
}


case $1 in
	start)
		if daemon_status; then
			echo "Transmission daemon already running!"
			exit 0
		else
			echo "Starting transmission daemon..."
			start_daemon
			exit $?
		fi
		;;
	stop)
		echo -n "Stopping transmission daemon..."
		stop_daemon
		exit 0
		;;
	restart)
		stop_daemon
		start_daemon
		exit $?
		;;
	status)
		if daemon_status; then
			echo "Running"
			exit 0
		else
			echo "Not running"
			exit 1
		fi
		;;
	log)
		echo $TRLOG
		exit 0
		;;
	*)
		exit 1
		;;
esac
