#!/bin/sh
# Copyright 2010 Antoine Bertin
# <diaoulael [ignore this] at users.sourceforge period net>
#
# This file is part of syno-packager.
#
# syno-packager is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# syno-packager is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with syno-packager.  If not, see <http://www.gnu.org/licenses/>.

UPGRADELOCK=/tmp/dyndns-updater.upgrade.lock

preinst ()
{
	# Check if Python is installed
	if [ ! -d /usr/local/Python ]; then
		echo "Python SPK is not installed. Install it and try again."
		exit 1
	fi

	exit 0
}

postinst ()
{
	# Create the view directory
	mkdir -p /usr/local/dyndns-updater

	# Create symlinks to the installation ditectory
	ln -s ${SYNOPKG_PKGDEST}/var /usr/local/dyndns-updater/var
	ln -s ${SYNOPKG_PKGDEST}/bin /usr/local/dyndns-updater/bin

	# Correct the files ownership
	chown -R root:root ${SYNOPKG_PKGDEST}

	# Correct the files permission
	chmod 770 /usr/local/dyndns-updater/var/*
	chmod 770 /usr/local/dyndns-updater/bin/*

	exit 0
}

preuninst ()
{
	exit 0
}

postuninst ()
{
	# Remove symlinks from /usr/local/dyndns-updater
	rm -f /usr/local/dyndns-updater/var
	rm -f /usr/local/dyndns-updater/bin

	# Remove the view directory
	rmdir /usr/local/dyndns-updater

	exit 0
}

preupgrade ()
{
	touch $UPGRADELOCK

	exit 0
}

postupgrade ()
{
	rm -f $UPGRADELOCK

	exit 0
}
